# Generated by Django 4.0.2 on 2022-02-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='is_trainer',
            field=models.BooleanField(default=False),
        ),
    ]
